### ISSUE TITLE
How align the close icon in center instead of on the top

### ISSUE THREAD

**Issue by usamamashkoor** [mouse0270/bootstrap-notify#121]
Hi 
i have searched all the documentation but i did not find any solution of this
How align the close icon in center instead of on the top
their is a close class on the message but it is also a bootstrap class so it disturbs the other alerts on my site 
here is my code
                       $.notify({
				// options
				message: 'msg'
			},{
				// settings
				type: 'success'
			},{
				icon: 'glyphicon glyphicon-star'
			}
			);
Kindly help me on this.
Thanks in advance

**Comment by mouse0270** [comment]
You should be able to add this to your css file. This will specify only the close in the notify. you may need to change the `margin-right` it should be half the size of your close button width.
``` css
.close[data-notify="dismiss"] {
    right: 50% !important;
    margin-right: -6px !important;
}
```

If this works, please let me know and close this issue. If you need anything else let me know.
