### ISSUE TITLE
Problems on Firefox (Linux) -working on Chrome-

### ISSUE THREAD

**Issue by rubensa** [mouse0270/bootstrap-notify#125]
A video from default demo page (http://bootstrap-notify.remabledesigns.com/), with same (default) configuration:
Left: Chrome Version 46.0.2490.80 (64-bit)
Right: Firefox 42.0

https://youtu.be/68HXUcnuNrc

**Comment by rubensa** [comment]
May be related to https://github.com/mouse0270/bootstrap-notify/issues/97

**Comment by mouse0270** [comment]
It is can you try adding something like this to your css file:

``` css
[data-notify="container"] {
  -moz-animation-iteration-count: 1;
  animation-iteration-count: 1;
}
```
