### ISSUE TITLE
Alerts just FLASH and Disappear in Firefox 45.0.1

### ISSUE THREAD

**Issue by dschueler** [mouse0270/bootstrap-notify#137]
In Firefox 45.0.1 Alerts flash on then off.....very annoying ;)

**Comment by mouse0270** [comment]
Please try adding the following css:

``` css
[data-notify="container"] {
  -moz-animation-iteration-count: 1;
  animation-iteration-count: 1;
}
```
