### ISSUE TITLE
Error on firefox.

### ISSUE THREAD

**Issue by gustavokataoka** [mouse0270/bootstrap-notify#144]
I tried on firefox and the notify goes on infinite show, fade... show, fade... even when i click to show one time. I didn't tried on my code, I tried only on your demo page.
The version of my firefox is 46.0.

**Comment by mouse0270** [comment]
Firefox by default sets `animation-iteration-count` to `infinite` where every other browser sets this to `1` You need to include the following in your css to resolve the issue. This is on my list to fix. I apologize for the inconvenience.
``` css
[data-notify="container"] {
  -moz-animation-iteration-count: 1;
  animation-iteration-count: 1;
}
```
