### ISSUE TITLE
Animation stuck in the loop in Firefox 38

### ISSUE THREAD

**Issue by eleweek** [mouse0270/bootstrap-notify#97]
Hi, I'm having this issue in Firefox 38 on OS X (But people confirmed it on different OSes: windows, linux(ubuntu)). 

Basically, using the demo, I press "Generate notification", and here is what I get: http://i.imgur.com/DmMcRoc.gif

**Comment by mouse0270** [comment]
Please add the following line to your css:

``` css
[data-notify="container"] {
  animation-iteration-count: 1;
}
```

I am having an issue with my keyboard and am unable to type certain characters and must use the on-screen keyboard until my new keyboard arrives. Until I am better able to fix this please use the css above.

**Comment by aribronstein** [comment]
Also a problem in Chrome 43.0.2357.124 on Windows

**Comment by mouse0270** [comment]
Yeah, I haven't been able to find a Javascript/jQuery Solution to this problem which means one of two things. 

1. I am going to have to start including a css file with about 10 lines of css (Will most likely remove most css from jQuery and add to file)
2. Tell people they need to include the following lines of CSS
``` css
[data-notify="container"] {
  animation-iteration-count: 1 !important;
}
```

I am still trying to find a solution using Javascript/jQuery because it would annoy me to have to include such a small css file because of one issue. I may not be able to though and my have to start including a css file.
