### ISSUE TITLE
Animation doesn't work

### ISSUE THREAD

**Issue by henry1778** [mouse0270/bootstrap-notify#99]
I use this code:

$.notify({
	// options
	icon: 'glyphicon glyphicon-warning-sign',
	title: 'Bootstrap notify',
	message: 'Turning standard Bootstrap alerts into "notify" like notifications',
	url: 'https://github.com/mouse0270/bootstrap-notify',
	target: '_blank'
},{
	// settings
	element: 'body',
	position: null,
	type: "info",
	allow_dismiss: true,
	newest_on_top: false,
	showProgressbar: false,
	placement: {
		from: "top",
		align: "right"
	},
	offset: 20,
	spacing: 10,
	z_index: 1031,
	delay: 6000,
	timer: 1000,
	url_target: '_blank',
	mouse_over: 'pause',
	animate: {
		enter: 'animated fadeInDown',
		exit: 'animated fadeOutUp'
	},
	onShow: null,
	onShown: null,
	onClose: null,
	onClosed: null
});
    
    
}, 7000); 

Everything works fine; but I can't see the animation effect on start and at the end. Is there an error?
I use jquery-1.11.0 and Bootstrap 3.

**Comment by mouse0270** [comment]
Are you using [Animate.css](http://daneden.github.io/animate.css/) or your own custom css animations?

**Comment by henry1778** [comment]
I have to include specific .css only for the animations?

**Comment by mouse0270** [comment]
Yes, you do please read the [documentation](http://bootstrap-notify.remabledesigns.com/).

**Comment by henry1778** [comment]
Ok, thanks. In my specific case, Can I choose only the parts relative fadeInDown and fadeOutUp effect?

**Comment by mouse0270** [comment]
One second, I'll copy and past the css for those animations.

**Comment by mouse0270** [comment]
``` css
@-webkit-keyframes fadeInDown {
  0% {
    opacity: 0;
    -webkit-transform: translate3d(0, -100%, 0);
    transform: translate3d(0, -100%, 0);
  }

  100% {
    opacity: 1;
    -webkit-transform: none;
    transform: none;
  }
}

@keyframes fadeInDown {
  0% {
    opacity: 0;
    -webkit-transform: translate3d(0, -100%, 0);
    transform: translate3d(0, -100%, 0);
  }

  100% {
    opacity: 1;
    -webkit-transform: none;
    transform: none;
  }
}

.fadeInDown {
  -webkit-animation-name: fadeInDown;
  animation-name: fadeInDown;
}

@-webkit-keyframes fadeOutUp {
  0% {
    opacity: 1;
  }

  100% {
    opacity: 0;
    -webkit-transform: translate3d(0, -100%, 0);
    transform: translate3d(0, -100%, 0);
  }
}

@keyframes fadeOutUp {
  0% {
    opacity: 1;
  }

  100% {
    opacity: 0;
    -webkit-transform: translate3d(0, -100%, 0);
    transform: translate3d(0, -100%, 0);
  }
}

.fadeOutUp {
  -webkit-animation-name: fadeOutUp;
  animation-name: fadeOutUp;
}
```
